// src/components/BotCard.tsx
import { Avatar } from "react-daisyui";
import { IObj } from "../utils/interfaces";
import React from "react";
import NextLink from "next/link";
import TuDropdownBtn from "./TuDropdownBtn";
import { api } from "../utils/constants";
import { activateBot, clearBotOrders, sleep } from "../utils/funcs";
interface IProps {
    bot: IObj;
    updateBot?: (bot: IObj) => void;
}

const BotCard: React.FC<IProps> = ({ bot, updateBot }) => {

    

    return (
        <NextLink
            href={`/bots/${bot._id}`}
            className="border-1 border-card bg-base-200 p-4 br-10 bot-card"
        >
            <div className="flex gap- justify-between">
                <div className="flex gap-4  overflow-hidden">
                    <div>
                        <Avatar
                            online={bot.active}
                            offline={!bot.active}
                            borderColor="neutral"
                            shape="circle"
                            innerClassName="ring relative w-35px h-35px flex items-center justify-center"
                        >
                            <span>
                                <i className="fi fi-br-user-robot"></i>
                            </span>
                        </Avatar>
                    </div>
                    <div className="overflow-hidden">
                        <h4 className="text-gray-200 fw-6">{bot.name}</h4>
                        <h6 className="fs-11 fw-6 text-gray-300">
                            {bot.base}/{bot.ccy}
                        </h6>
                        <div className="mt-1 overflow-hidden">
                            <p
                                className="fs-13"
                                style={{
                                    textOverflow: "ellipsis",
                                    whiteSpace: "nowrap",
                                    overflow: "hidden",
                                    flexGrow: 0,
                                }}
                            >
                                {bot.desc}
                            </p>
                        </div>
                    </div>
                </div>
                <div className="">
                    <TuDropdownBtn
                        toggler={
                            <button className="btn btn-ghost btn-circle fs-20 fw-7">
                                <span>
                                    <i className="fi fi-rr-circle-ellipsis"></i>
                                </span>
                            </button>
                        }
                        items={[
                            {
                                child: (
                                    <span>
                                        {bot.active ? "Deactivate" : "Activate"}
                                    </span>
                                ),
                                onTap: async (e)=> await activateBot(e.target.parentElement, bot, updateBot),
                            },
                            {child: <span >Clear orders</span>, onTap: async (e)=> await clearBotOrders(e.target.parentElement, bot, updateBot), disabled: !bot.orders.length}
                        ]}
                    />
                </div>
            </div>
        </NextLink>
    );
};
export default BotCard;

// components/BotCard.vue
<template>
    <NuxtLink
        :to="`/bots/${bot._id}`"
        class="border-1 border-card bg-base-200 p-4 br-10 bot-card"
    >
        <div class="flex gap- justify-between">
            <div class="flex gap-4 overflow-hidden">
                <div>
                    <UAvatar
                        :chip-color="bot.active ? 'primary' : 'yellow'"
                        borderColor="neutral"
                        shape="circle"
                        innerclass="ring relative w-35px h-35px flex items-center justify-center"
                    >
                        <span>
                            <i class="fi fi-br-user-robot"></i>
                        </span>
                    </UAvatar>
                </div>
                <div class="overflow-hidden">
                    <h4 class="text-gray-200 fw-6 fs-14">{{ bot.name }}</h4>
                    <h6 class="fs-11 fw-6 text-gray-400">
                        {{ bot.base }}/{{ bot.ccy }}
                    </h6>
                    <div class="mt-1 overflow-hidden">
                        <p
                            class="fs-13"
                            style="
                                text-overflow: ellipsis;
                                white-space: nowrap;
                                overflow: hidden;
                            "
                        >
                            {{ bot.desc }}
                        </p>
                    </div>
                </div>
            </div>
            <div class="">
                <CtxMenu
                    :open="menuOpen"
                    :set-is-open="(val : boolean) =>menuOpen = val"
                >
                    <template v-slot:toggler>
                        <UButton variant="ghost" color="gray-500"
                            ><span class="fs-16">
                                <i class="fi fi-rr-circle-ellipsis"></i> </span
                        ></UButton>
                    </template>
                    <template v-slot:children>
                        <li @click="activateBot(($event.target as any).parentElement, bot, updateBot)"><span>{{ bot.active ? 'Deactivate' : 'Activate' }}</span></li>
                        <li :class="!bot.orders.length ? 'disabled' : ''"  @click="clearBotOrders(($event.target as any).parentElement, bot, updateBot)"><span>Clear orders</span></li>
                    </template>
                </CtxMenu>
            </div>
        </div>
    </NuxtLink>
</template>
<script setup lang="ts">
const menuOpen = ref(false);
defineProps({
    bot: { type: Object, required: true },
    updateBot: { type: Function },
});
</script>
