// src/components/Navbar.tsx
import NextLink from 'next/link'
import { SITE } from '../utils/constants';

const Navbar = () => {
    return ( <div className="navbar">
    <div className="navbar-start">
        <div className="dropdown">
            <label tabIndex={0} className="btn btn-ghost btn-circle">
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-5 w-5"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                >
                    <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        d="M4 6h16M4 12h16M4 18h7"
                    />
                </svg>
            </label>
            <ul
                tabIndex={0}
                className="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52"
            >
                <li><a>Homepage</a></li>
                <li><a>Portfolio</a></li>
                <li><a>About</a></li>
            </ul>
        </div>
    </div>
    <div className="navbar-center">
        <a href="/" className="btn btn-ghost normal-case text-xl">{SITE}</a>
    </div>
    <div className="navbar-end">
        <ul className="menu menu-horizontal p-0 px-1 md:flex hidden">
            <li>
                <NextLink href="/about">About</NextLink>
            </li>
            <li>
                <NextLink href="/contact">Contact us</NextLink>
            </li>
        </ul>
    <button tabIndex={0} className="btn btn-ghost btn-circle">
            <i className="material-icons">search</i>
        </button>
        <button className="btn btn-ghost btn-circle">
            <div className="indicator">
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-5 w-5"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                >
                    <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="2"
                        d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9"
                    />
                </svg>
                <span
                    className="badge badge-xs badge-primary indicator-item"
                ></span>
            </div>
        </button>
    </div>
</div> );
}
 
export default Navbar;

// components/Navbar.vue
<template>
       <div class="navbar">
            <div class="navbar-start">
                <div class="dropdown">
                    <label tabindex="0" class="btn btn-ghost btn-circle">
                        <svg
                            xmlns="http://www.w3.org/2000/svg"
                            class="h-5 w-5"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke="currentColor"
                        >
                            <path
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                stroke-width="2"
                                d="M4 6h16M4 12h16M4 18h7"
                            />
                        </svg>
                    </label>
                    <ul
                        tabindex="0"
                        class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow bg-base-100 rounded-box w-52"
                    >
                        <li><a>Homepage</a></li>
                        <li>
                        <NuxtLink to="/@enid">Enid</NuxtLink>
                    </li>
                        <li>
                        <NuxtLink to="/ce">CE</NuxtLink>
                    </li>
      
                    </ul>
                </div>
            </div>
            <div class="navbar-center">
                <a href="/" class="btn btn-ghost normal-case text-xl">{{SITE}}</a>
            </div>
            <div class="navbar-end">
             
            <button tabindex="0" class="btn btn-ghost btn-circle">
                    <i class="fi fi-rr-search"></i>
                </button>
                <button class="btn btn-ghost btn-circle">
                    <div class="indicator">
                        <span><i class="fi fi-rr-bell"></i></span>
                        <span
                            class="badge badge-xs badge-primary indicator-item"
                        ></span>
                    </div>
                </button>
                       <CtxMenu :open="menuOpen" :set-is-open="(val : boolean) =>menuOpen = val">
                        <template v-slot:toggler>
                        <div class="avatar btn btn-sm btn-circle ml-4">
                            <div class="w-25px h-25px rounded-full ring text-center"> <span class="text-xl fw-7">T</span></div>
                        </div>
                     </template>
                     <template v-slot:children>
                        <li> <span>Item 1</span></li>
                        <li> <span>Item 1</span></li>
                        <li> <span>Item 1</span></li>
             
                    </template>
                        
                    </CtxMenu>
            </div>
        </div>
</template>

<script setup lang="ts">
    const menuOpen = ref(false)
</script>
