// src/components/Sidebar.tsx
import NextLink from 'next/link'

const Sidebar = () => {
    return (     <aside >
        <ul className="menu gap-0 sm:gap-5  sidebar">
   
    
   <li className="tooltip tooltip-right" data-tip="Home"> 
       <NextLink href="/">
        <i className="fi fi-rr-home"></i>
       </NextLink>
   </li>
   <li className="tooltip tooltip-right" data-tip="Backtest">
       <NextLink href="/backtest">
        <i className="fi fi-rr-blood-test-tube-alt"></i>
       </NextLink>
   </li>
   <li className="tooltip tooltip-right" data-tip="Contact us">
       <NextLink href="/contact">
        <i className="fi fi-rr-envelope"></i>
       </NextLink>
   </li>
   <li className="tooltip tooltip-right" data-tip="About us">
       <NextLink href="/about">
        <i className="fi fi-rr-info"></i>
       </NextLink>
   </li>
</ul>
    </aside> );
}
 
export default Sidebar;

// components/Sidebar.vue
<template>
    <aside >
        <ul class="menu gap-0 sm:gap-5  sidebar">
   
    
   <li class="tooltip tooltip-right" data-tip="Home">
       <NuxtLink to="/">
        <i class="fi fi-rr-home"></i>
       </NuxtLink>
   </li>
   <li class="tooltip tooltip-right" data-tip="Backtest">
       <NuxtLink to="/backtest">
        <i class="fi fi-rr-blood-test-tube-alt"></i>
       </NuxtLink>
   </li>
<!--    <li class="tooltip tooltip-right" data-tip="Contact us">
       <NuxtLink to="/contact">
        <i class="fi fi-rr-envelope"></i>
       </NuxtLink>
   </li>
   <li class="tooltip tooltip-right" data-tip="About us">
       <NuxtLink to="/about">
        <i class="fi fi-rr-info"></i>
       </NuxtLink>
   </li> -->
</ul>
    </aside>
</template>

<script setup lang="ts"></script>
