// src/pages/auth/login/index.tsx
import { ReactElement, useEffect, useRef, useState } from "react";
import NextLink from "next/link";
import $ from "jquery";
import { api, SITE, STORAGE_KEYS } from "@/src/utils/constants";
import Layout2 from "@/src/components/Layout2";
import { IObj } from "@/src/utils/interfaces";
import TuMeta from "@/src/components/TuMeta";
import { useRouter } from "next/router";
import { setUser } from "@/src/redux/reducers/user";
import { useDispatch } from "react-redux";

const SignupPage = () => {
    const [btnDisabled, setBtnDisabled] = useState(false);
    const [passType, setPassType] = useState("password");
    const [err, setErr] = useState("");

    const formRef = useRef<any>();
    const router = useRouter()
    const dispatch = useDispatch()

    const submitForm = async (e:any) => { 
        e.preventDefault()
        const form = e.target
        const btn: HTMLButtonElement = form.querySelector('button')
        try{
            btn.textContent = "..."
            setErr("")
            setBtnDisabled(true)
            
            const formData = {username: form.username.value, password: form.password.value}
            console.log(formData);
            const res = await api().post('/auth/login', formData)
            console.log(res.data);
            dispatch(setUser(res.data.user))
            localStorage.setItem(STORAGE_KEYS.authTkn, res.data.token)
            setTimeout(()=>{setBtnDisabled(false)}, 1500)

            location.href = router.query.red as string ?? "/"

        }catch(e: any){
            console.log(e)
            btn.textContent = "Retry"
            setBtnDisabled(false)
            const _err = typeof e.response?.data == "string" && e.response?.data?.startsWith("tuned:") ? e.response.data.replace("tuned:", "") : "Something went wrong"
            setErr(_err)
            
        }
     }
    return (
        <div>
            <TuMeta title={`Login - ${SITE}`}/>
            
                <form ref={formRef} id="si-form" autoComplete="off" onSubmit={submitForm}>
                    <fieldset className="formset m-auto border-card border-1 px-5 pb-5">
                        <legend className="text-primary"><NextLink href="/">{SITE}</NextLink></legend>
                        <h2 className="text-cente my-3 fw-6">Login</h2>
                        <div className="form-group">
                            <label>
                                <div className="label">
                                    <span className="label-text">Email or username</span>
                                </div>{" "}
                                <input
                                    type="text"
                                    name="username"
                                    required
                                    className=" input input-bordered"
                                    placeholder="Enter email or username..."
                                />
                            </label>
                        </div>
                        <div className="form-group">
                            <label className="">
                                <div className="label">
                                    <span className="label-text">Password</span>
                                </div>
                                <div className="flex items-center gap-2 input input-bordered">
                                    <input
                                        auto-complete="off"
                                        type={passType}
                                        id="pass"
                                        name="password"
                                        required
                                        className="grow"
                                        placeholder="Enter password..."
                                        pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}"
                                        title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters"
                                    />
                                    {passType == "password" ? (
                                        <span
                                            onClick={() => {
                                                setPassType("text");
                                            }}
                                            className="btn-none"
                                            title="show password"
                                        >
                                            <i className="fi fi-rr-eye"></i>
                                        </span>
                                    ) : (
                                        <span
                                            className="btn-none"
                                            onClick={() => {
                                                setPassType("password");
                                            }}
                                            title="hide password"
                                        >
                                            <i className="fi fi-rr-eye-crossed"></i>
                                        </span>
                                    )}
                                </div>
                               
                            </label>
                        </div>
                    
                        {err?.length != 0 && <div className="mt-2 ml-2 text-whit fs-12 text-center text-warning"><p >{err?.replace("tuned:", "")}</p></div>}
                        <div className="mt-2 form-group ">
                            <button
                                type="submit"
                                disabled={btnDisabled}
                                id="su-btn"
                                className="su-btn btn btn-primary w-100p"
                            >
                                Login
                            </button>
                        </div>
                        <div className="form-group text-center mt-3 fs-14">
                            <p>
                               Or{" "}
                                <NextLink
                                    href="/auth/signup"
                                    className="text-primary"
                                >
                                    Create an account
                                </NextLink>
                            </p>
                        </div>
                    </fieldset>
                </form>
        </div>
    );
};
SignupPage.getLayout = function getLayout(page: ReactElement) {
    return <Layout2>{page}</Layout2>;
};
export default SignupPage;

// pages/auth/login.vue
<template>
    <div>
        <TMeta :title="`Login - ${SITE}`"/>
        <div class="flex items-center justify-center w-100p h-80vh" >
            <UForm :state="formState" @submit="submitForm">
                <fieldset class="formset m-auto border-card border-1 px-5 pb-5">
                    <legend class="text-primary text-xl text-cente"><NuxtLink to="/">{{SITE}}</NuxtLink></legend>
                    <h2 class="text-cente my-3 fw-6">Login</h2>
                    <div class="mt-1 flex flex-col gap-2">
                        <UFormGroup label="Email/Username">
                            <UInput placeholder="Enter email or username..." required v-model="formState.username"/>
                        </UFormGroup>
                        <UFormGroup label="Password">
                            <UInput :ui="{ icon: { trailing: { pointer: '' } } }" placeholder="Enter password..." :type="passType" required v-model="formState.password">
                            <template #trailing>
                                <span class="pointer" @click="()=>{
                                    console.log('object');
                                    passType == 'text' ? setPassType('password') : setPassType('text')}">
                                    <i v-if="passType == 'password'" class="fi fi-rr-eye"></i>
                                    <i v-else class="fi fi-rr-eye-crossed"></i>
                                </span>
                            </template>
                            </UInput>
                        </UFormGroup>
                        <div v-if="err.length" class="ml-2 text-whit fs-12 text-center text-red-200"><p >{{ err?.replace("tuned:", "")}}</p></div>
                        <UFormGroup class="mt-1">
                            <UButton :disabled="!formState.username?.length || !formState.password?.length" class="w-full" type="submit" label="Login"/>
                        </UFormGroup>
                        <UFormGroup>
                            <p class="fs-14 text-center">Or <NuxtLink class="text-primary" to="/auth/signup">Create account</NuxtLink></p>
                        </UFormGroup>
                    </div>
                </fieldset>
            </UForm>
        </div>
    </div>
</template>
<script lang="ts" setup>
import { useUserStore } from '~/src/stores/user';

    const btnDisabled = ref(false), setBtnDisabled = (v: boolean)=> btnDisabled.value = v;
    const passType = ref("password"), err = ref(""), setPassType = (v: string) => passType.value = v, setErr = (v: string) => err.value = v;
    const route = useRoute()
    const { setUser } = useUserStore()
    const formState  = reactive<IObj>({
        
    })

    const submitForm = async (e:any) => { 

        try{
            setErr("")
            setBtnDisabled(true)
            
            const formData = formState
            console.log(formData);
            const res = await api().post('/auth/login', formData)
            console.log(res.data);
            setUser(res.data.user)
            localStorage.setItem(STORAGE_KEYS.authTkn, res.data.token)
            setTimeout(()=>{setBtnDisabled(false)}, 1500)

            location.href = route.query.red as string ?? "/"

        }catch(e: any){
            console.log(e)
            setBtnDisabled(false)
            const _err = typeof e.response?.data == "string" && e.response?.data?.startsWith("tuned:") ? e.response.data.replace("tuned:", "") : "Something went wrong"
            setErr(_err)
            
        }
     }

    definePageMeta({layout: 'blank'})
</script>
