// components/TuForm.vue
<template>
    <form @submit="_onSubmit" ref='formRef' action="">
        <slot/>
    </form>
</template>
<script setup lang="ts">
const props = defineProps({
    onSubmit: Function,
})

const _onSubmit = async (e: any)=>{
    e.preventDefault()
    const btns = [...e.target.querySelectorAll('button[type=submit]')]
    btns.forEach((btn: any)=>{
        btn.disabled = true})
    if (props.onSubmit){
        await props.onSubmit(e)}
    btns.forEach((btn: any)=>btn.disabled = false)
}
</script>

// src/components/TuForm.tsx
import React from "react";

const TuForm = ({
    onSubmit,
    children,
}: {
    onSubmit: Function;
    children: React.ReactNode;
}) => {
    const handleSubmit = async (e: any) => {
        console.log("ON SUBMIT");
        e.preventDefault();
        const btns = [...e.target.querySelectorAll("button[type=submit]")];
        btns.forEach((btn: any) => {
            btn.disabled = true;
        });
        if (onSubmit) {
            await onSubmit(e);
        }
        btns.forEach((btn: any) => (btn.disabled = false));
    };
    return (
        <form action="#" onSubmit={handleSubmit}>
            {children}
        </form>
    );
};

export default TuForm;
