// src/pages/bots/[id]/index.tsx
import BotFormModal from "@/src/components/BotFormModal";
import TuMeta from "@/src/components/TuMeta";
import TuStat from "@/src/components/TuStat";
import { RootState } from "@/src/redux/store";
import { SITE, api, selectIntervals, selectSymbols } from "@/src/utils/constants";
import { activateBot, toSelectStrategies } from "@/src/utils/funcs";
import { IObj } from "@/src/utils/interfaces";
import Error from "next/error";
import { FC, useEffect, useState } from "react";
import { Checkbox, Stats, Textarea } from "react-daisyui";
import { JSONTree } from "react-json-tree";
import { useSelector } from "react-redux";

interface IProps {
    bot: IObj;
    err?: IObj;
}
const theme = {
    scheme: "monokai",
    author: "Tonni Diaz",
    base00: "#1d232a",
    base01: "#383830",
    base02: "#49483e",
    base03: "#75715e",
    base04: "#a59f85",
    base05: "#f8f8f2",
    base06: "#f5f4f1",
    base07: "#f9f8f5",
    base08: "#f92672",
    base09: "#fd971f",
    base0A: "#f4bf75",
    base0B: "#a6e22e",
    base0C: "#a1efe4",
    base0D: "#66d9ef",
    base0E: "#ae81ff",
    base0F: "#cc6633",
};
export const getServerSideProps = async ({ query }: { query: IObj }) => {
    try {
        const res = await api().get("/bots/" + query.id);

        return { props: { bot: res.data } };
    } catch (e: any) {
        console.log(e);
        const code = e.response?.status ?? 500;
        const _err =
            typeof e.response?.data == "string" &&
            e.response?.data?.startsWith("tuned:")
                ? e.response.data.replace("tuned:", "")
                : "Something went wrong";
        return { props: { err: { code, msg: _err } } };
    }
};

const BotPage: FC<IProps> = ({ bot, err }) => {
    const [_bot, setBot] = useState<IObj>({});
    const [botModal, setBotModal] = useState<HTMLDialogElement>();

    const appStore = useSelector((state: RootState) => state.app);

    useEffect(() => {
        if (bot) setBot(bot);
        console.log(bot);
    }, [bot]);

    useEffect(() => {
        
    }, []);
    return err ? (
        <Error statusCode={err.code} title={err.msg} />
    ) : (
        <div className="md:p-5 p-1">
            <TuMeta title={`Bot: ${_bot.name} - ${SITE}`} />

            <fieldset className="formset border-card border-1 p-2 md:p-4">
                <legend>
                    <h1 className="text-gray-200">{_bot.name}</h1>
                </legend>
                <div className="flex gap-4 justify-center items-center">
                    <span className="fw-8">
                        {_bot.base}/{_bot.ccy}
                    </span>{" "}
                    {_bot.active ? (
                        <div className="badge badge-success">Active</div>
                    ) : (
                        <div className="badge badge-warning">Paused</div>
                    )}
                </div>
                <div className="flex gap-4 justify-center mt-3 items-center">
                    <button
                        onClick={(e) =>
                            activateBot(e.currentTarget, _bot, setBot)
                        }
                        className="btn btn-neutral btn-sm"
                    >
                        {_bot.active ? "Deactivate" : "Activate"}
                    </button>
                    <button
                        className="btn btn-sm btn-rounded btn-neutral"
                        title="Modify"
                        onClick={(_) => botModal?.showModal()}
                    >
                        <span>
                            <i className="fi fi-br-pencil"></i>
                        </span>
                    </button>
                </div>
                <div className="mt-">
                    <div className="stats text-center flex">
                        <div className="stat m-auto">
                            <span className="stat-title">Total orders:</span>
                            <span className="stat-value">
                                {_bot.orders?.length ?? 0}
                            </span>
                        </div>
                    </div>
                    <div>
                        <details className="collapse collapse-arrow border border-card bg-base-100">
                            <summary className="collapse-title text-xl font-medium">
                                More details
                            </summary>
                            <div className="collapse-content">
                                <div className="form-group flex items-center gap-3 justify-center">
                                    <label htmlFor="demo" className="label">
                                        Demo mode
                                    </label>
                                    <Checkbox
                                        id="demo"
                                        checked={_bot.demo}
                                        readOnly
                                    />
                                </div>
                                <div className="shadow grid grid-cols-2">
                                    <TuStat
                                        title="Start amount"
                                        value={_bot.start_amt ?? 0}
                                    />
                                    <TuStat
                                        title="Current amount"
                                        value={_bot.curr_amt ?? 0}
                                    />
                                    <TuStat
                                        title="Interval"
                                        value={`${_bot.interval}m`}
                                    />
                                    <TuStat
                                        title="Strategy"
                                        valClasses="wp-wrap"
                                        value={appStore.strategies[_bot.strategy]?.name}
                                    />
                                </div>
                                <div className="mt-1">
                                    <Textarea
                                        placeholder="Description..."
                                        readOnly
                                        value={_bot.desc}
                                    />
                                </div>
                            </div>
                        </details>
                    </div>
                    <fieldset className="formset border-1 border-card  p-2 mt-2">
                        <legend>Orders</legend>
                        <div className="mt-2 overflow-y-scroll">
                            {_bot.orders?.map((el: IObj, i: number) => (
                                <div key={`item-${i * 1}`}>
                                    <JSONTree
                                        theme={theme}
                                        keyPath={["Order"]}
                                        data={el}
                                        shouldExpandNodeInitially={(k, d, l) =>
                                            false
                                        }
                                    />
                                </div>
                            ))}
                        </div>
                    </fieldset>
                </div>
            </fieldset>

            <BotFormModal
                fd={{
                    name: bot.name,
                    desc: bot.desc,
                    demo: bot.demo,
                    id: bot._id,
                    pair: selectSymbols.find(
                        (el) =>
                            el.value.toString() ==
                            [bot.base, bot.ccy].toString()
                    ),
                    strategy: toSelectStrategies(appStore.strategies).find(
                        (el) => el.value == bot.strategy
                    ),
                    interval: selectIntervals.find(
                        (el) => el.value == bot.interval
                    ),
                
                }}
                setRef={setBotModal}
                mode="Edit"
                onDone={(bot) => setBot(bot)}
            />
        </div>
    );
};

export default BotPage;

// pages/bots/[id]/index.vue
<template>
    <div v-if="_bot">
        <TMeta :title="`${_bot.name} - ${SITE}`" />
        <fieldset class="fieldset w-full sm:w-96 m-auto border-card border-1 p-2 md:p-4">
            <legend>
                <h1 class="text-gray-200">{{ _bot.name }}</h1>
            </legend>
            <div class="flex gap-4 justify-center items-center">
                <span class="fw-8"> {{ _bot.base }}/{{ _bot.ccy }} </span>
                <UBadge
                    :label="_bot.active ? 'Active' : 'Paused'"
                    :color="_bot.active ? 'primary' : 'yellow'"
                    class="badge badge-success"
                />
            </div>
            <div class="flex gap-4 justify-center mt-3 items-center">
                <UButton
                    @click="(e : any)=> activateBot(e.currentTarget, _bot!, (val: any)=> _bot = val)"
                    class="btn btn-neutral btn-sm"
                    color="gray"
                >
                    {{ _bot.active ? "Deactivate" : "Activate" }}
                </UButton>
                <UButton
                    class="btn btn-sm btn-rounded btn-neutral"
                    title="Modify"
                    color="gray"
                    @click="
                        (_) => {
                            /*  botModal?.showModal() */
                        }
                    "
                >
                    <span>
                        <i class="fi fi-br-pencil"></i>
                    </span>
                </UButton>
            </div>
            <div class="my-3">
                <TuStats
                    class="items-center justify-center gap-2"
                    :stats="[
                        {title: 'L:', subtitle: _bot.orders?.filter((el: any) => el.profit < 0)
                                    ?.length ?? 0, click: ()=> orderType = EOrder.lose},
                        {title: 'Total orders:', subtitle: _bot.orders
                                    ?.length ?? 0, click: ()=> orderType = EOrder.all},
                        {title: 'W:', subtitle: _bot.orders?.filter((el: any) => el.profit > 0)
                                    ?.length ?? 0, click: ()=> orderType = EOrder.win},
                                    ]"
                >
                </TuStats>
            </div>
            <div class="flex flex-col gap-2">
                <UAccordion :items="moreInfo">
                    <template #item>
                        <div class="flex flex-col gap-2 items-center">
                            <UFormGroup>
                                <UCheckbox
                                    label="Demo mode"
                                    disabled
                                    :modelValue="_bot.demo"
                                />
                            </UFormGroup>
                            <TuStats
                                :stats="[
                                    {
                                        title: 'Start amount',
                                        subtitle: _bot.start_amt ?? 0,
                                    },
                                    {
                                        title: 'Current amount',
                                        subtitle: (_bot.orders
                                            ? _bot.orders[
                                                  _bot.orders.length - 1
                                              ].ccy_amt
                                            : 0
                                        ).toFixed(2),
                                    },
                                ]"
                            />
                            <TuStats
                                :stats="[
                                    {
                                        title: 'Interval',
                                        subtitle: `${_bot.interval}m`,
                                    },
                                    {
                                        title: 'Strategy',
                                        subtitle:
                                            strategies[_bot.strategy - 1]
                                                ?.name ?? 'null',
                                    },
                                ]"
                            />

                            <div class="mt-1">
                                <UTextarea
                                    placeholder="Bot description"
                                    disabled
                                    :model-value="_bot.desc"
                                />
                            </div>
                        </div>
                    </template>
                </UAccordion>
                <UAccordion multiple :items="[{ label: 'Orders' }]">
                    <template #item>
                        <div class="flex flex-col gap-2 items-center pl-4">
                            <UAccordion
                                v-for="(order, i) in _bot.orders ?? []"
                                :items="[
                                    {
                                        label: `${i + 1}. ${order.base}/${
                                            order.ccy
                                        } \t [${order.side}]`,
                                    },
                                ]"
                            >
                                <template #item>
                                    <div class="flex flex-col gap-3 font-monospace all">
                                        <div class="">
                                            <p class="flex justify-between">
                                                <span class="text-heading fw-6"
                                                    >Buy ID:</span
                                                >
                                                <span>{{
                                                    order.buy_order_id
                                                }}</span>
                                            </p>
                                            <p class="flex justify-between">
                                                <span class="text-heading fw-6"
                                                    >Sell ID:</span
                                                >
                                                <span>{{
                                                    order.order_id.length
                                                        ? order.order_id
                                                        : "-- -- --"
                                                }}</span>
                                            </p>
                                        </div>
                                            <div>
                                                <h6 class="fw-6">Entry time</h6>
                                                <div
                                                    class="flex justify-between ml-3"
                                                >
                                                    <span
                                                        class="text-heading fw-6"
                                                        >In:</span
                                                    ><span>{{ order.buy_timestamp?.i ?
                                                        new Date(
                                                            order.buy_timestamp?.i
                                                        )
                                                            .toISOString()
                                                            .slice(0, 16) : '-- -- --'
                                                    }}</span>
                                                </div>
                                                <div
                                                    class="flex justify-between ml-3"
                                                >
                                                    <span
                                                        class="text-heading fw-6"
                                                        >Out:</span
                                                    ><span>{{ order.buy_timestamp?.o ?
                                                        new Date(
                                                            order.buy_timestamp?.o
                                                        )
                                                            .toISOString()
                                                            .slice(0, 16) : '-- -- --'
                                                    }}</span>
                                                </div>
                                            </div>
                                            <div>
                                                <h6 class="fw-6">Exit time</h6>
                                                <div
                                                    class="flex justify-between ml-3"
                                                >
                                                    <span
                                                        class="text-heading fw-6"
                                                        >In:</span
                                                    ><span>{{
                                                      order.sell_timestamp?.i ?  new Date(
                                                            order.sell_timestamp?.i
                                                        )
                                                            .toISOString()
                                                            .slice(0, 16) : '-- -- --'
                                                    }}</span>
                                                </div>
                                                <div
                                                    class="flex justify-between ml-3"
                                                >
                                                    <span
                                                        class="text-heading fw-6"
                                                        >Out:</span
                                                    ><span>{{ order.sell_timestamp?.o  ?
                                                        new Date(
                                                            order.sell_timestamp?.o
                                                        )
                                                            .toISOString()
                                                            .slice(0, 16) : '-- -- --'
                                                    }}</span>
                                                </div>
                                            </div>
                                            <p class="flex justify-between"><span class="fw-6 text-heading">Entry price:</span><span>{{ order.ccy }} {{ order.ccy_amt }}</span></p>
                                            <p class="flex justify-between"><span class="fw-6 text-heading">Exit price:</span><span>{{ order.ccy }} {{ order.new_ccy_amt }}</span></p>
                                            <p class="flex justify-between"><span class="fw-6 text-heading">Base amount:</span><span>{{ order.base }} {{ order.base_amt }}</span></p>
                                            <p class="flex justify-between"><span class="fw-6 text-heading">Buy fee:</span><span>{{ order.base }} {{ order.buy_fee }}</span></p>
                                            <p class="flex justify-between"><span class="fw-6 text-heading">Sell fee:</span><span>{{ order.ccy }} {{ order.sell_fee }}</span></p>
                                        <div class="grid grid-cols-2"></div>
                                    </div>
                                </template>
                            </UAccordion>
                        </div>
                    </template>
                </UAccordion>
            </div>
        </fieldset>
        <BotFormModal
            mode="Edit"
            :bot="{
                name: _bot.name,
                desc: _bot.desc,
                demo: _bot.demo,
                id: _bot._id,
                symbol: [_bot.base, _bot.ccy],
                /* pair: selectSymbols.find(
                        (el) =>
                            el.value.toString() ==
                            [_bot.base, _bot.ccy].toString()
                    ),
                   strategy: toSelectStrategies(appStore.strategies).find(
                        (el) => el.value == _bot.strategy
                    ),
                    interval: selectIntervals.find(
                        (el) => el.value == _bot.interval
                    ), */
            }"
            v-model="modalOpen"
        />
    </div>
</template>

<script setup lang="ts">
import { useAppStore } from "~/src/stores/app";

const { strategies } = storeToRefs(useAppStore());

enum EOrder {
    all,
    win,
    lose,
}
const _bot = ref<IObj>(),
    modalOpen = ref(false),
    orders = ref<IObj[]>([]),
    orderType = ref<EOrder>(EOrder.all);

const route = useRoute();
const id = ref(route.params.id);

const moreInfo = [{ label: "More info", content: "Lorem Ipsum" }];

const { data, error } = await useTuFetch<any>("/api/bots/" + id.value, {
    watch: [id],
});
if (error.value) {
    console.log(error.value.statusCode);
    throw createError({
        statusCode: error.value?.statusCode,
        statusMessage: error.value.statusMessage,
    });
}

const filterOrders = (val: any[]) => {
    orders.value = val.filter((el: IObj) =>
        orderType.value == EOrder.win
            ? el.prifit > 0
            : orderType.value == EOrder.lose
            ? el.profit < 0
            : true
    );
};
onMounted(() => {
    const bot = data.value;
    _bot.value = bot;
    //setOrders(bot.orders);
    if (bot.orders) filterOrders(bot.orders);
});

watch(orderType, (val) => {
    filterOrders(data.value.orders);
});
</script>
